# DataSource Config
spring:
  datasource:
    name: springbootDemo
    password: 935377012
    username: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#mybatis
mybatis-plus:
  mapper-locations: classpath:com/pxc/mybatisplus/*/mapper/*Mapper.xml #如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置
  type-aliases-package: classpath:com.pxc.mybatisplus.*.entity
#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# Logger Config
logging:
  level:
    com.pxc.mybatisplus: debug